# Generated by Django 4.0.6 on 2022-07-18 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(max_length=100)),
                ('sem1', models.CharField(max_length=100)),
                ('sem2', models.CharField(max_length=100)),
                ('sem3', models.CharField(max_length=100)),
                ('sem4', models.CharField(max_length=100)),
            ],
        ),
    ]
